[package]
name = "pirs"
description = "A POSIX-like shell written in Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { version = "0.2", features = ["const-extern-fn", "extra_traits"] }

owo-colors = { version = "3.2", optional = true }
supports-unicode = { version = "1.0", optional = true }

rustyline = { version = "9.1", optional = true }
dirs = { version = "4.0", optional = true }

[profile.release]
lto = true
strip = "symbols"

[[bin]]
name = "pirs"
required-features = ["cli"]

[features]
default = ["cli"]

use-default-logger = ["owo-colors", "supports-unicode"]
cli = ["rustyline", "use-default-logger", "dirs"]
