[package]
name = "pirs"
description = "A portable POSIX-like shell written in Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
supports-unicode = { git = "https://github.com/pirs-sh/supports-unicode" }

owo-colors = { version = "3.2", optional = true }

rustyline = { version = "9.1", optional = true }
dirs = { version = "4.0", optional = true }

[profile.release]
lto = true
# FIXME: uncomment when Cargo version 1.59 is stable
# strip = "symbols"

[[bin]]
name = "pirs"
required-features = ["cli"]

[features]
default = ["cli"]

use-default-logger = ["owo-colors"]
cli = ["rustyline", "use-default-logger", "dirs"]
