[package]
name = "pirs"
description = "A portable Bash-like shell written in Rust"
version = "0.0.8"
repository = "https://github.com/pirs-rs/pirs"
homepage = "https://pirs.ml"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
supports-unicode--used-for-pirs = "1.0.3" # { git = "https://github.com/pirs-rs/supports-unicode" }

rustyline = { version = "9.1", optional = true }
dirs = { version = "4.0", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", optional = true }
web-sys = { version = "0.3", optional = true, features = ["Element"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
owo-colors = { version = "3.2", optional = true }
tokio = { version = "1.17", features = ["rt-multi-thread", "macros"] }

[profile.release]
lto = true
strip = "symbols"

[[bin]]
name = "pirs"
required-features = ["cli"]

[features]
exit-on-drop = []
default-logger = ["owo-colors", "wasm-bindgen", "web-sys"]
cli = ["rustyline", "default-logger", "dirs"]
