[package]
name = "pirs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.9"
libc = { version = "0.2", features = ["const-extern-fn", "extra_traits"] }

owo-colors = { version = "3.2", optional = true }

[profile.release]
lto = true

[[bin]]
name = "pirs"
required-features = ["use-default-logger"]

[features]
use-default-logger = ["owo-colors"]
